App.factory 'WasteItems', -> [
  {name: 'Aerosol Cans (empty)', category: 'Recyclable'},
  {name: 'Aerosol Cans (not empty)', category: 'Hazardous Waste'},
  {name: 'Aluminum Cans & Foil', category: 'Recyclable'},
  {name: 'Aluminum Foil (soiled)', category: 'Garbage'},
  {name: 'Auto Parts', category: 'Drop-off'},
  {name: 'Bakery Trays', category: 'Recyclable'},
  {name: 'Batteries', category: 'Hazardous Waste'},
  {name: 'Batteries - Hearing Aid', category: 'Drop-off'},
  {name: 'Beverage Cans', category: 'Recyclable'},
  {name: 'Beverage Cartons', category: 'Recyclable'},
  {name: 'Bicycle', category: 'Drop-off'},
  {name: 'Blankets', category: 'Drop-off'},
  {name: 'Bleach tubs/lids', category: 'Recyclable'},
  {name: 'Bones', category: 'Yard Waste'},
  {name: 'Books', category: 'Drop-off'},
  {name: 'Bottles', category: 'Recyclable'},
  {name: 'Boxboard', category: 'Recyclable'},
  {name: 'Bread', category: 'Yard Waste'},
  {name: 'Bread bags', category: 'Recyclable'},
  {name: 'Broken Glass', category: 'Garbage'},
  {name: 'Broken Toys', category: 'Garbage'},
  {name: 'Brown paper bags', category: 'Yard Waste'},
  {name: 'Building Supplies', category: 'Drop-off'},
  {name: 'Cake', category: 'Yard Waste'},
  {name: 'Candies', category: 'Yard Waste'},
  {name: 'Candy Wrappers', category: 'Garbage'},
  {name: 'Carbon Paper', category: 'Garbage'},
  {name: 'Cardboard', category: 'Recyclable'},
  {name: 'Cardboard with metal bottoms', category: 'Recyclable'},
  {name: 'Cards', category: 'Garbage'},
  {name: 'Carpet', category: 'Large Item'},
  {name: 'Catalogues', category: 'Recyclable'},
  {name: 'CDs, DVDs, Videos, Video Games', category: 'Drop-off'},
  {name: 'Ceramics', category: 'Garbage'},
  {name: 'Cereal boxes', category: 'Recyclable'},
  {name: 'CFL Lightbulbs', category: 'Drop-off'},
  {name: 'Chicken', category: 'Yard Waste'},
  {name: 'Children\'s Items', category: 'Drop-off'},
  {name: 'Chip Bags', category: 'Garbage'},
  {name: 'Cleaning Liquids (Corrosive)', category: 'Hazardous Waste'},
  {name: 'Cloth items', category: 'Garbage'},
  {name: 'Clothes Hangers', category: 'Drop-off'},
  {name: 'Clothing (reusable)', category: 'Drop-off'},
  {name: 'Coffee Cups (paper only)', category: 'Yard Waste'},
  {name: 'Coffee filters', category: 'Yard Waste'},
  {name: 'Coffee grounds', category: 'Yard Waste'},
  {name: 'Comforters', category: 'Drop-off'},
  {name: 'Commercial Waste', category: 'Drop-off'},
  {name: 'Compost', category: 'Yard Waste'},
  {name: 'Computer', category: 'Drop-off'},
  {name: 'Construction Materials', category: 'Drop-off'},
  {name: 'Construction Paper', category: 'Yard Waste'},
  {name: 'Cookie Boxes', category: 'Recyclable'},
  {name: 'Cool fireplace ashes', category: 'Yard Waste'},
  {name: 'Cutlery', category: 'Garbage'},
  {name: 'Dairy products', category: 'Yard Waste'},
  {name: 'Dead Animals - Call your local Humane Society', category: 'None'},
  {name: 'Dehumidifier', category: 'Large Item'},
  {name: 'Detergent tubs/lids', category: 'Recyclable'},
  {name: 'Diapers', category: 'Garbage'},
  {name: 'Dishes (broken)', category: 'Garbage'},
  {name: 'Dishes (Used)', category: 'Garbage'},
  {name: 'Dishwasher', category: 'Large Item'},
  {name: 'Dough', category: 'Yard Waste'},
  {name: 'Draperies', category: 'Drop-off'},
  {name: 'Drink Boxes', category: 'Recyclable'},
  {name: 'Dry Cleaning bags', category: 'Recyclable'},
  {name: 'Dryer lint', category: 'Yard Waste'},
  {name: 'Egg Cartons - Paper', category: 'Yard Waste'},
  {name: 'Egg Shells', category: 'Yard Waste'},
  {name: 'Eggs', category: 'Yard Waste'},
  {name: 'Electronics', category: 'Drop-off'},
  {name: 'Envelopes', category: 'Recyclable'},
  {name: 'Explosives - call a non-emergency number', category: 'None'},
  {name: 'Eyeglasses', category: 'Drop-off'},
  {name: 'Fatty Foods', category: 'Yard Waste'},
  {name: 'Feces (Pet)', category: 'Yard Waste'},
  {name: 'Fireworks (used)', category: 'Garbage'},
  {name: 'Fish Scraps', category: 'Yard Waste'},
  {name: 'Floor sweepings', category: 'Garbage'},
  {name: 'Flour and grains', category: 'Yard Waste'},
  {name: 'Flowers (cut)', category: 'Yard Waste'},
  {name: 'Fluorescent light tubes', category: 'Hazardous Waste'},
  {name: 'Flyers', category: 'Recyclable'},
  {name: 'Foam Packaging', category: 'Recyclable'},
  {name: 'Foil Containers', category: 'Recyclable'},
  {name: 'Fridge / Freezer', category: 'Large Item'},
  {name: 'Frozen juice cans', category: 'Recyclable'},
  {name: 'Fruit scraps', category: 'Yard Waste'},
  {name: 'Furniture', category: 'Drop-off'},
  {name: 'Gasoline', category: 'Hazardous Waste'},
  {name: 'Gift Boxes', category: 'Recyclable'},
  {name: 'Gift Wrapping Paper', category: 'Garbage'},
  {name: 'Glass Jars', category: 'Recyclable'},
  {name: 'Glasses (drinking)', category: 'Garbage'},
  {name: 'Glasses (prescription)', category: 'Drop-off'},
  {name: 'Grass clippings', category: 'None'},
  {name: 'Grocery bags', category: 'Recyclable'},
  {name: 'Hair Clippings', category: 'Yard Waste'},
  {name: 'Hardcover books (no cover)', category: 'Recyclable'},
  {name: 'Hearing Aids', category: 'Drop-off'},
  {name: 'Herbicides', category: 'Hazardous Waste'},
  {name: 'Humidifier', category: 'Large Item'},
  {name: 'Ice cream tubs/lids', category: 'Recyclable'},
  {name: 'Infected Plants', category: 'Yard Waste'},
  {name: 'Instruments', category: 'Drop-off'},
  {name: 'Jewellery', category: 'Drop-off'},
  {name: 'Juice bottles/tubs/lids', category: 'Recyclable'},
  {name: 'Kitchen Appliances', category: 'Drop-off'},
  {name: 'Kitchen Utensils', category: 'Drop-off'},
  {name: 'Latex Gloves', category: 'Garbage'},
  {name: 'Leaves', category: 'Yard Waste'},
  {name: 'Legal Drugs', category: 'Hazardous Waste'},
  {name: 'Lightbulbs', category: 'Garbage'},
  {name: 'Lights, Fluorescent tubes', category: 'Hazardous Waste'},
  {name: 'Liquid Paint', category: 'Hazardous Waste'},
  {name: 'Magazines', category: 'Drop-off'},
  {name: 'Margarine tubs/lids', category: 'Recyclable'},
  {name: 'Meat', category: 'Yard Waste'},
  {name: 'Microwave popcorn bags', category: 'Yard Waste'},
  {name: 'Microwaves', category: 'Large Item'},
  {name: 'Milk bags', category: 'Recyclable'},
  {name: 'Milk Cartons', category: 'Recyclable'},
  {name: 'Motor Oil', category: 'Hazardous Waste'},
  {name: 'Motor Oil bottles/tubs/lids', category: 'Recyclable'},
  {name: 'Muffins', category: 'Yard Waste'},
  {name: 'Musical items', category: 'Drop-off'},
  {name: 'Needles & Syringes', category: 'Hazardous Waste'},
  {name: 'Newspapers', category: 'Recyclable'},
  {name: 'Nuts and nutshells', category: 'Yard Waste'},
  {name: 'Oil - Cooking', category: 'Yard Waste'},
  {name: 'Oil - Motor', category: 'Hazardous Waste'},
  {name: 'Organics', category: 'Yard Waste'},
  {name: 'Paint Cans - empty', category: 'Recyclable'},
  {name: 'Paint Cans - not empty', category: 'Hazardous Waste'},
  {name: 'Paper', category: 'Recyclable'},
  {name: 'Paper take-out trays/cups/plates', category: 'Yard Waste'},
  {name: 'Paper Towel - not soiled', category: 'Yard Waste'},
  {name: 'Paperbacks', category: 'Recyclable'},
  {name: 'Pasta', category: 'Yard Waste'},
  {name: 'Peelings', category: 'Yard Waste'},
  {name: 'Pesticides', category: 'Hazardous Waste'},
  {name: 'Pet hair and feathers', category: 'Yard Waste'},
  {name: 'Pet waste and kitty litter bag', category: 'Yard Waste'},
  {name: 'Pharmaceuticals', category: 'Hazardous Waste'},
  {name: 'Phone Books', category: 'Recyclable'},
  {name: 'Pies', category: 'Yard Waste'},
  {name: 'Pizza boxes', category: 'Recyclable'},
  {name: 'Plants (trimmings/house plants)', category: 'Yard Waste'},
  {name: 'Plastic Bags', category: 'Recyclable'},
  {name: 'Plastic Bottles', category: 'Recyclable'},
  {name: 'Plastic Cups/lids', category: 'Recyclable'},
  {name: 'Plastic Liners', category: 'Garbage'},
  {name: 'Plastic Wrap (used)', category: 'Garbage'},
  {name: 'Polystyrene Foam Plastic', category: 'Recyclable'},
  {name: 'Pop cases', category: 'Recyclable'},
  {name: 'Popsicle sticks', category: 'Yard Waste'},
  {name: 'Potato Chip Bags', category: 'Garbage'},
  {name: 'Pots and Pans', category: 'Drop-off'},
  {name: 'Printer Cartridges', category: 'Drop-off'},
  {name: 'Propane Tanks', category: 'Hazardous Waste'},
  {name: 'Purses', category: 'Drop-off'},
  {name: 'Pyrex', category: 'Garbage'},
  {name: 'Rice', category: 'Yard Waste'},
  {name: 'Rubber Gloves', category: 'Garbage'},
  {name: 'Sauces, gravy and dressings', category: 'Yard Waste'},
  {name: 'Saw dust', category: 'Yard Waste'},
  {name: 'Scrap Metal', category: 'Drop-off'},
  {name: 'Shampoo bottles/lids', category: 'Recyclable'},
  {name: 'Sharps', category: 'Hazardous Waste'},
  {name: 'Shellfish', category: 'Yard Waste'},
  {name: 'Shoes', category: 'Drop-off'},
  {name: 'Shredded Paper', category: 'Recyclable'},
  {name: 'Smoke Detectors', category: 'Garbage'},
  {name: 'Soiled newsprint', category: 'Yard Waste'},
  {name: 'Solvents', category: 'Hazardous Waste'},
  {name: 'Sport equipment', category: 'Drop-off'},
  {name: 'Spray Paint (empty)', category: 'Recyclable'},
  {name: 'Spray Paint (not empty)', category: 'Hazardous Waste'},
  {name: 'Stove', category: 'Large Item'},
  {name: 'Straw', category: 'Yard Waste'},
  {name: 'Styrofoam', category: 'Recyclable'},
  {name: 'Tea Bags', category: 'Yard Waste'},
  {name: 'Thinners', category: 'Hazardous Waste'},
  {name: 'Tire Rims', category: 'Drop-off'},
  {name: 'Tires', category: 'Drop-off'},
  {name: 'Toothpaste Tubes', category: 'Garbage'},
  {name: 'Toothpicks', category: 'Yard Waste'},
  {name: 'Toys', category: 'Drop-off'},
  {name: 'Twigs', category: 'Yard Waste'},
  {name: 'Vacuum Bags', category: 'Garbage'},
  {name: 'Vacuums', category: 'Drop-off'},
  {name: 'Vegetable scraps', category: 'Yard Waste'},
  {name: 'Wallpaper', category: 'Garbage'},
  {name: 'Water bottles/tubs/lids', category: 'Recyclable'},
  {name: 'Waxed Paper', category: 'Garbage'},
  {name: 'Weeds', category: 'Yard Waste'},
  {name: 'Windshield washer bottles', category: 'Recyclable'},
  {name: 'Wood Chips', category: 'Yard Waste'},
  {name: 'Wooden Stir Sticks', category: 'Yard Waste'},
  {name: 'Yogurt Lids (foil)', category: 'Garbage'},
  {name: 'Yogurt Lids (plastic)', category: 'Recyclable'},
]
